# Use the official Golang image as the base image
FROM golang:latest

# Set the working directory to /app
WORKDIR /app

# Clone the Postmanerator repository
RUN git clone https://github.com/aubm/postmanerator.git

# Change the working directory to /app/postmanerator
WORKDIR /app/postmanerator

# Build Postmanerator from the source
RUN go build

# Add the Postman collection file to the container
COPY go-echo-boilerplate.postman_collection.json /app/postmanerator/mycollection.json

# COPY dev.postman_environment.json /app/to/environment.json
# Set the entrypoint to run Postmanerato
ENTRYPOINT ["/app/postmanerator/postmanerator"]